You can add notes here

```{r}
#install necessary packages
# install.packages(dplyr)
library(dplyr)
```

```{r}
# reading in dataset
data <- read.csv("data/train.csv")

head(data)

```

Notes

```{r}
#reduced dataset
data_small <- select(data, YearBuilt, BedroomAbvGr, FullBath, OverallQual, OverallCond, BldgType, GarageQual, Neighborhood, MSZoning, LotArea, GrLivArea, SalePrice)
#area dataset
data_area <- select(data, LotArea, )
```

```{r}
## average prices per variable
# Neighborhood and sale price
avg_neigh <- summarise(group_by(data_small, Neighborhood),
          price = mean(SalePrice))
avg_neigh

# Zoning and sale price
avg_zone <- summarise(group_by(data_small, MSZoning),
                    price = mean(SalePrice))
avg_zone
# year and sale price
avg_cond <- summarise(group_by(data_small, OverallCond),
                      price = mean(SalePrice))
```

```{r}
yr_num <- summarise(group_by(data, YearBuilt),
          yr_count = n())
data_combined <- arrange(full_join(data_small, yr_num), YearBuilt)
```

```{r}
avg_price <- full_join(avg_neigh, avg_zone, by = "price")
avg_price
```

```{r}
summarise(group_by(data, BsmtQual),
          count = n())
```

```{r}
data_dif <-data |>
  select(YearBuilt, YearRemodAdd) |>
  mutate(difference = YearRemodAdd - YearBuilt)
nrow(filter(data_dif, difference > 3))
nrow(data_dif)
```

```{r}
data_dif1 <- data |>
  select(YearBuilt, GarageYrBlt) |>
  mutate(garagedif = GarageYrBlt - YearBuilt)
nrow(filter(data_dif1, garagedif > 0))
nrow(filter(data, YearRemodAdd == YrSold))
```

```{r}
tail(arrange(data, YearRemodAdd))
```

```{r}
summarise(group_by(data, HouseStyle),
          count = n())
```
